@echo off 
@REM HOW TO EXECUTE : JUST OPEN THIS FILE IN TERMINAL USING ./build.bat (windows users)

set BUILD_DIRECTORY=build
set FILE_NAME=form_uvatool
set UI_FILE=%FILE_NAME%.ui
SET OUTPUT_FILE=%BUILD_DIRECTORY%\%FILE_NAME%.py

@REM CREATING BUILD FOLDER OUTPUT
if exist %BUILD_DIRECTORY% (
  echo BUILD FOLDER ALREADY EXIST
) else (
  mkdir %BUILD_DIRECTORY%
)

@REM PROCESSING UI FILE
echo EXECUTING: pyuic5 -x %UI_FILE% -o %OUTPUT_FILE%
pyuic5 -x %UI_FILE% -o %OUTPUT_FILE%

echo SCRIPT ENDING...